#   Nupicter - Hand operated picture filtering tool
#   Copyright (C) 2021  Arkadiusz Choruzy
#
#   Arkadiusz Choruzy
#   achoruzy@gmail.com

"""Nupicter's module for editing Picture objects created by FileHandler module.

Picture class handles objects converted to [[[R, G, B], [R, G, B], ...], ...] format
and includes methods for edition of such files.
"""

import numpy as np


class Picture():
    """The class handles objects that may be edited by its methods and saved as files
    or returned as another Picture class object.

    Args:
        img: pixel list generated by FileHandler. 
    """

    def __init__(self, img):

        self.pixels = img

    def as_array(self):
        """Method for creating numpy type array for the object.

        Returns:
            numpy.array object
        """
        # selfcheck try/except to develop
        return np.asarray(self.pixels)

    def save(self):
        pass

    def return_picture(self):
        pass


if __name__ == '__main__':
    pass
